repo:
  owner: generic-provider-testing
  workflow_id: "run.yaml"
  ref: main

mlflow:
  experiment:
    name: "diego-24"
  credentials:
    secretRef:
      namespace: mlflow-system
      name: azure-token
      key: access_token
  run:
    name: "mlflow-run-default"
    alpha: "0.5"
    metrics:
      - "mse"



